[workspace.package]
name = "rust_terminal"
authors = ["PaNDa2code"]
version = "0.0.0"

[workspace]
members = [
  "circular_buffer",
  "main_app",
]

[workspace.dependencies]
windows = { version = "0.59.0", features = ["Win32_System_Memory", "Win32_System_SystemInformation", "Win32_Security"] }
