[package]
edition = "2021"
name = "console_session"
authors.workspace = true
version.workspace = true

[dependencies]
windows = { workspace = true }

circular_buffer = { path = "../circular_buffer" }
